version: '3.3'
services:
  postgres:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_DB=testbd'